name: Run market_env_report.py

on:
  schedule:
    - cron: '0 1 * * *'   # 每日 01:00 UTC（台北時間約 09:00）
  workflow_dispatch:        # 允許手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib schedule requests python-dateutil

      - name: Run market_env_report.py
        env:
          # 建議在 Repo Settings → Secrets and variables → Actions 設定以下變數
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          # 若沒設定，以下提供預設，避免空值造成程式中斷
          SMTP_SERVER: ${{ secrets.SMTP_SERVER || 'smtp.gmail.com' }}
          SMTP_PORT: ${{ secrets.SMTP_PORT || '587' }}
          SEND_TIME: '09:00'   # 您的程式若使用到可保留；不使用可刪
          TZ: Asia/Taipei
        run: python market_env_report.py
